services:
    db: 
        image: postgres:16.3-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD variable is not set}
            - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB variable is not set}
        volumes:
            - type: bind
              source: ./postgresql
              target: /var/lib/postgresql/data
    redis:
        image:  redis:7.0.15-alpine
        command:
            - /bin/sh
            - -c
            # - Double dollars, so that the variable is not expanded by Docker Compose
            # - Surround by quotes, so that the shell does not split the password
            # - The ${variable:?message} syntax causes shell to exit with a non-zero
            #   code and print a message, when the variable is not set or empty
            - redis-server --requirepass ${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}
        ports:
            - 6379:6379
        volumes:
            - type: bind
              source: ./redis
              target: /data
    quiz:
        build:
            context: .
            dockerfile_inline: |
                FROM node:lts-alpine AS base
                COPY package.json package-lock.json /quiz/
                RUN echo /quiz/
                WORKDIR /quiz
                RUN npm i
                COPY . /quiz 

                FROM base AS quiz-prod
                RUN npm run build 
                CMD ["node", "/quiz/.output/server/index.mjs"]

                FROM base AS quiz-dev
                CMD ["npm", "run", "dev"]

                FROM quiz-${BUILD:?BUILD must be either 'dev' or 'prod'}
                RUN echo "BUILD ${BUILD}"
        ports:
            - 3000:3000
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /quiz/
                - action: rebuild
                  path: ./package.json
networks:
    default:
        name: test
        ipam:
            driver: default
            config:
                - subnet: "192.168.200.0/24"

volumes:
    fast-quiz:
