production:
  dialect: postgres
  datasource: ${POSTGRES_CONNECTION}
  dir: migrations
  table: migrations

development:
  dialect: postgres
  datasource: ${POSTGRES_CONNECTION}
  dir: migrations
  table: migrations
